### ISSUE TITLE
Rook Movement Bug

### ISSUE THREAD

**Issue by Nilslof** [Nilslof/nilslof-chess#1]
Identify, locate and fix a bug where a rook can move into the pawn in front of it at the start of the game

**Comment by violaso** [comment]
### Cause

The rank of pieces behind the first rank of white pawns is black. Therefor it's perfectly right of the rook to long for some pawn.

![image](https://user-images.githubusercontent.com/55837845/65708887-d9c4a880-e08f-11e9-9dea-200f0ff17db3.png)

**Comment by violaso** [comment]
### Fixed issue

Copy paste laziness caused this one.

![image](https://user-images.githubusercontent.com/55837845/65709591-6f146c80-e091-11e9-8ba0-ca1522aff7c7.png)

Fixed two issues in one!
